[package]
name = "mastermind"
version = "0.1.0"
authors = ["basile.du.plessis"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
itertools = "0.9"